### PR TITLE
build(windows): asciinema not build

### PR DESCRIPTION
**Pull request by Kristinita**
*(Sorry, it issue, not pull request; but issues are disabled for this repository)*

### 1. Summary

In header.

### 2. Environment

+ Operating system:

	+ Windows 10 Enterprise LTSB 64-bit EN (local)
	+ Windows Server 2016 (AppVeyor)

+ Go 1.10.0 x64

See [**another pre-installed software**](https://www.appveyor.com/docs/build-environment/#pre-installed-software), if needed.

### 3. Steps to reproduce

See [**`appveyor.yml` file**](https://github.com/Kristinita/SashaAppVeyorDebugging/blob/SashaAsciinema/appveyor.yml) of SashaAsciinema branch of my demo repository.

As [**you say**](https://github.com/asciinema/asciinema/issues/150#issuecomment-375151554):

```shell
mkdir \path\to\your\gopath\src\github.com\mattn
cd \path\to\your\gopath\src\github.com\mattn
git clone https://github.com/mattn/asciinema
cd asciinema
git checkout windows
go build
```

### 4. Expected behavior

Successful asciinema for Windows build.

### 5. Actual behavior

See [**AppVeyor build**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging/build/1.0.33).

```go
go build
main.go:11:2: cannot find package "github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/docopt/docopt-go" in any of:
	C:\go\src\github.com\asciinema\asciinema\Godeps\_workspace\src\github.com\docopt\docopt-go (from $GOROOT)
	c:\gopath\src\github.com\asciinema\asciinema\Godeps\_workspace\src\github.com\docopt\docopt-go (from $GOPATH)
main.go:12:2: cannot find package "github.com/asciinema/asciinema/api" in any of:
	C:\go\src\github.com\asciinema\asciinema\api (from $GOROOT)
	c:\gopath\src\github.com\asciinema\asciinema\api (from $GOPATH)
main.go:13:2: cannot find package "github.com/asciinema/asciinema/commands" in any of:
	C:\go\src\github.com\asciinema\asciinema\commands (from $GOROOT)
	c:\gopath\src\github.com\asciinema\asciinema\commands (from $GOPATH)
main.go:14:2: cannot find package "github.com/asciinema/asciinema/util" in any of:
	C:\go\src\github.com\asciinema\asciinema\util (from $GOROOT)
	c:\gopath\src\github.com\asciinema\asciinema\util (from $GOPATH)
main.go:15:2: cannot find package "github.com/mattn/go-colorable" in any of:
	C:\go\src\github.com\mattn\go-colorable (from $GOROOT)
	c:\gopath\src\github.com\mattn\go-colorable (from $GOPATH)
Command exited with code 1
```

Thanks.

### CODE REVIEW

**Comment by mattn** [comment]
please try this.

```
mkdir \path\to\your\gopath\src\github.com\mattn
cd \path\to\your\gopath\src\github.com\mattn
git clone https://github.com/mattn/asciinema
cd asciinema
git checkout windows
go get -d 
go build
```

**Comment by Kristinita** [comment]
**Status: :x: Not fixed**

See [**AppVeyor build**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging/build/1.0.34):

```go
go get -d
package github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/docopt/docopt-go: cannot find package "github.com/asciinema/asciinema/Godeps/_workspace/src/github.com/docopt/docopt-go" in any of:
    C:\go\src\github.com\asciinema\asciinema\Godeps\_workspace\src\github.com\docopt\docopt-go (from $GOROOT)
    c:\gopath\src\github.com\asciinema\asciinema\Godeps\_workspace\src\github.com\docopt\docopt-go (from $GOPATH)
package github.com/asciinema/asciinema/api: cannot find package "github.com/asciinema/asciinema/api" in any of:
    C:\go\src\github.com\asciinema\asciinema\api (from $GOROOT)
    c:\gopath\src\github.com\asciinema\asciinema\api (from $GOPATH)
package github.com/asciinema/asciinema/commands: cannot find package "github.com/asciinema/asciinema/commands" in any of:
    C:\go\src\github.com\asciinema\asciinema\commands (from $GOROOT)
    c:\gopath\src\github.com\asciinema\asciinema\commands (from $GOPATH)
package github.com/asciinema/asciinema/util: cannot find package "github.com/asciinema/asciinema/util" in any of:
    C:\go\src\github.com\asciinema\asciinema\util (from $GOROOT)
    c:\gopath\src\github.com\asciinema\asciinema\util (from $GOPATH)
Command exited with code 1
```

Thanks.

**Comment by tylerbutler** [comment]
Build worked for me using the following steps (note the different path in the first two steps):

```
mkdir \path\to\your\gopath\src\github.com\asciinema
cd \path\to\your\gopath\src\github.com\asciinema
git clone https://github.com/mattn/asciinema
cd asciinema
git checkout windows
go get -d
go build
```

**Comment by Kristinita** [comment]
**Status: :heavy_check_mark: Fixed for me**

+ [**AppVeyor build**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging)
+ [**asciinema demo**](https://asciinema.org/a/180874)

@tylerbutler, thanks!

@mattn, can you add to documentation steps to build asciinema for Windows?

**Comment by mattn** [comment]
If anyone send pull-request to me, I'll merge it.

**Comment by mo-han** [comment]
Well, the build steps above really does not work now, for me.
My specs: win10 x86_64 (10.0.10240 LTSB 2015), go version go1.11.4 windows/amd64.
When I tried to build this forenoon, `go` keeps asking me for two another repos of yours: `go-colorable` and `go-isatty`. I have to `git clone` those two and then build successfully.

BTW, though `go build` does not spend long, could you just release pre-built `.exe` binary all-together? And here is my build.
[asciinema-windows-win10-x86_64-go1.11.4-mattn-2fd0cd0.zip](https://github.com/mattn/asciinema/files/2771551/asciinema-windows-win10-x86_64-go1.11.4-mattn-2fd0cd0.zip)
https://www.virustotal.com/#/file/8713de6426cbb7840c201a1bede54155baf7d996c048ca8608fc4d24357c19bf/detection

**Pull request closed without merging**
